// generated from rosidl_generator_c/resource/idl.h.em
// with input from microstrain_inertial_msgs:msg/MipFilterAidingMeasurementSummaryIndicator.idl
// generated code does not contain a copyright notice

#ifndef MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_FILTER_AIDING_MEASUREMENT_SUMMARY_INDICATOR_H_
#define MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_FILTER_AIDING_MEASUREMENT_SUMMARY_INDICATOR_H_

#include "microstrain_inertial_msgs/msg/detail/mip_filter_aiding_measurement_summary_indicator__struct.h"
#include "microstrain_inertial_msgs/msg/detail/mip_filter_aiding_measurement_summary_indicator__functions.h"
#include "microstrain_inertial_msgs/msg/detail/mip_filter_aiding_measurement_summary_indicator__type_support.h"

#endif  // MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_FILTER_AIDING_MEASUREMENT_SUMMARY_INDICATOR_H_
