// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_SENSOR_OVERRANGE_STATUS_STATUS_HPP_
#define MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_SENSOR_OVERRANGE_STATUS_STATUS_HPP_

#include "microstrain_inertial_msgs/msg/detail/mip_sensor_overrange_status_status__struct.hpp"
#include "microstrain_inertial_msgs/msg/detail/mip_sensor_overrange_status_status__builder.hpp"
#include "microstrain_inertial_msgs/msg/detail/mip_sensor_overrange_status_status__traits.hpp"
#include "microstrain_inertial_msgs/msg/detail/mip_sensor_overrange_status_status__type_support.hpp"

#endif  // MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_SENSOR_OVERRANGE_STATUS_STATUS_HPP_
