// generated from rosidl_generator_c/resource/idl.h.em
// with input from microstrain_inertial_msgs:msg/MipFilterGnssDualAntennaStatusStatusFlags.idl
// generated code does not contain a copyright notice

#ifndef MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_FILTER_GNSS_DUAL_ANTENNA_STATUS_STATUS_FLAGS_H_
#define MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_FILTER_GNSS_DUAL_ANTENNA_STATUS_STATUS_FLAGS_H_

#include "microstrain_inertial_msgs/msg/detail/mip_filter_gnss_dual_antenna_status_status_flags__struct.h"
#include "microstrain_inertial_msgs/msg/detail/mip_filter_gnss_dual_antenna_status_status_flags__functions.h"
#include "microstrain_inertial_msgs/msg/detail/mip_filter_gnss_dual_antenna_status_status_flags__type_support.h"

#endif  // MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_FILTER_GNSS_DUAL_ANTENNA_STATUS_STATUS_FLAGS_H_
