// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_SENSOR_TEMPERATURE_STATISTICS_HPP_
#define MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_SENSOR_TEMPERATURE_STATISTICS_HPP_

#include "microstrain_inertial_msgs/msg/detail/mip_sensor_temperature_statistics__struct.hpp"
#include "microstrain_inertial_msgs/msg/detail/mip_sensor_temperature_statistics__builder.hpp"
#include "microstrain_inertial_msgs/msg/detail/mip_sensor_temperature_statistics__traits.hpp"
#include "microstrain_inertial_msgs/msg/detail/mip_sensor_temperature_statistics__type_support.hpp"

#endif  // MICROSTRAIN_INERTIAL_MSGS__MSG__MIP_SENSOR_TEMPERATURE_STATISTICS_HPP_
